#!/usr/bin/env bash

# Demo script for testing user automation controls
# This script demonstrates the user flow for enabling/disabling automation

echo "========================================="
echo "User Automation Controls - Demo Script"
echo "========================================="
echo ""

echo "📋 Prerequisites:"
echo "  1. Smart contract deployed to testnet"
echo "  2. Frontend running (npm run dev)"
echo "  3. Backend orchestrator configured"
echo "  4. Test wallet with funds"
echo ""

read -p "Press Enter to start demo..."

echo ""
echo "=== STEP 1: User Setup ==="
echo "1. Connect wallet to frontend (http://localhost:3000)"
echo "2. Initialize AI agent with RWA collateral"
echo "3. Navigate to dashboard"
echo ""
read -p "✓ Completed? Press Enter to continue..."

echo ""
echo "=== STEP 2: Enable Automation ==="
echo "1. Find 'AI Automation' card on dashboard"
echo "2. Click 'Configure' button"
echo "3. Select strategy: [Conservative] [Balanced] [Aggressive]"
echo "4. Set max borrow: 100 USDC"
echo "5. Set cooldown: 5 minutes (300 seconds)"
echo "6. Click 'Enable Automation'"
echo "7. Approve transaction in wallet"
echo "8. Wait for confirmation"
echo ""
read -p "✓ Completed? Press Enter to continue..."

echo ""
echo "=== STEP 3: Verify Frontend Status ==="
echo "Expected results:"
echo "  • Status shows: ● Active (green)"
echo "  • Strategy displays: Balanced Strategy"
echo "  • Max Borrow: $100 USDC"
echo "  • Cooldown: 5 min"
echo "  • Message: 'Ready for next automated decision' OR countdown timer"
echo ""
read -p "✓ Verified? Press Enter to continue..."

echo ""
echo "=== STEP 4: Start Backend Orchestrator ==="
echo "In a new terminal:"
echo "  cd packages/ai-agents"
echo "  python -m src.main"
echo ""
echo "Expected logs:"
echo "  🚀 Starting multi-user agent loop..."
echo "  Found X users in contract"
echo "  --- Checking user 0x... ---"
echo "  ✅ User 0x... ready for automated decision"
echo "  Strategy: Balanced"
echo "  Action: BORROW_AND_INVEST (or HOLD)"
echo ""
read -p "✓ Backend running? Press Enter to continue..."

echo ""
echo "=== STEP 5: Watch First Decision ==="
echo "Wait for cooldown period (5 minutes)..."
echo ""
echo "Backend should show:"
echo "  --- Checking user 0x... ---"
echo "  ✅ User ready for automated decision"
echo "  Action: BORROW_AND_INVEST"
echo "  Executing decision on-chain..."
echo "  ✅ Transaction sent: 0x..."
echo "  ✅ Transaction confirmed"
echo ""
echo "Frontend should update:"
echo "  • Position appears in 'Investment Positions'"
echo "  • Borrowed USDC increases"
echo "  • Next decision countdown starts"
echo ""
read -p "✓ Decision executed? Press Enter to continue..."

echo ""
echo "=== STEP 6: Test Cooldown Period ==="
echo "Before cooldown expires:"
echo ""
echo "Backend should show:"
echo "  ⏸️ User in cooldown (XXs remaining)"
echo "  Processed 0 opted-in users, skipped 1"
echo ""
echo "Frontend should show:"
echo "  ⏸️ Next decision in Xm Ys"
echo ""
read -p "✓ Cooldown working? Press Enter to continue..."

echo ""
echo "=== STEP 7: Update Settings ==="
echo "On frontend:"
echo "1. Click 'Configure'"
echo "2. Change max borrow to 200 USDC"
echo "3. Change cooldown to 10 minutes"
echo "4. Click 'Update Settings'"
echo "5. Approve transaction"
echo ""
echo "Expected:"
echo "  ✅ Settings updated successfully!"
echo "  Max Borrow: $200 USDC"
echo "  Cooldown: 10 min"
echo ""
read -p "✓ Settings updated? Press Enter to continue..."

echo ""
echo "=== STEP 8: Disable Automation ==="
echo "On frontend:"
echo "1. Click 'Configure'"
echo "2. Click 'Disable' button (red)"
echo "3. Approve transaction"
echo ""
echo "Expected:"
echo "  Status changes to: ○ Inactive (gray)"
echo "  Message: 'Automation is disabled'"
echo ""
echo "Backend should show (next loop):"
echo "  ⏭️ User has automation disabled, skipping"
echo "  Processed 0 opted-in users, skipped 1"
echo ""
read -p "✓ Automation disabled? Press Enter to continue..."

echo ""
echo "=== STEP 9: Test Multiple Users ==="
echo "1. Connect second wallet"
echo "2. Initialize agent with collateral"
echo "3. Enable automation with different settings:"
echo "   - Conservative strategy"
echo "   - 50 USDC max borrow"
echo "   - 3 minutes cooldown"
echo ""
echo "Backend should show (next loop):"
echo "  Found 2 users in contract"
echo "  --- Checking user 0x... ---"
echo "  ⏭️ User has automation disabled, skipping"
echo "  --- Checking user 0x... ---"
echo "  ✅ User ready for automated decision"
echo "  Strategy: Conservative"
echo "  Processed 1 opted-in users, skipped 1"
echo ""
read -p "✓ Multiple users working? Press Enter to continue..."

echo ""
echo "=== STEP 10: Test Max Borrow Limit ==="
echo "If AI tries to borrow more than max:"
echo ""
echo "Backend should show:"
echo "  Decision: BORROW_AND_INVEST"
echo "  Borrow amount: 150 USDC"
echo "  ⚠️ Decision exceeds user's max borrow (150 > 100)"
echo "  Capping borrow amount to 100"
echo "  ✅ Executed with capped amount"
echo ""
read -p "✓ Limit enforced? Press Enter to continue..."

echo ""
echo "========================================="
echo "✅ Demo Complete!"
echo "========================================="
echo ""
echo "Summary of Features Tested:"
echo "  ✓ Enable automation with preferences"
echo "  ✓ Strategy selection (Conservative/Balanced/Aggressive)"
echo "  ✓ Max borrow enforcement"
echo "  ✓ Cooldown period enforcement"
echo "  ✓ Update settings"
echo "  ✓ Disable automation"
echo "  ✓ Multiple users with different settings"
echo "  ✓ Backend respects user preferences"
echo "  ✓ Frontend UI updates in real-time"
echo ""
echo "🎉 User Controls Implementation VERIFIED!"
echo ""
echo "Next Steps:"
echo "  • Deploy to testnet"
echo "  • Share with test users"
echo "  • Collect feedback"
echo "  • Fine-tune UX based on usage"
echo ""
